import type { Metadata } from "next";
// 1. Import both fonts
import localFont from "next/font/local";
import "./globals.css";

const hiragino = localFont({
  src: "./fonts/Hiragino.otf",
  variable: "--font-hiragino",
  weight: "800",
});

//Configured Lekton
const lekton = localFont({
  src: [
    {
      path: "./fonts/Lektonregular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Lektonbold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-lekton",
});

// 3. Configured Luckiest Guy
const luckiest = localFont({
  src: "./fonts/Luckiestguy.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-luckiest",
});

export const metadata: Metadata = {
  title: "Imaginbright",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lekton.variable} ${luckiest.variable} ${hiragino.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
