import type { Metadata } from "next";
// 1. Import both fonts
import localFont from "next/font/local";
import { Lekton, Luckiest_Guy } from "next/font/google";
import "./globals.css";

const hiragino = localFont({
  src: "./fonts/Hiragino.otf",
  variable: "--font-hiragino",
  weight: "800",
});

//Configured Lekton
const lekton = Lekton({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular and Bold
  variable: "--font-lekton",
});

// 3. Configured Luckiest Guy
const luckiest = Luckiest_Guy({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-luckiest",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lekton.variable} ${luckiest.variable} ${hiragino.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
